#Loading project sources

source("pipeline/main/runoff.R")
source("pipeline/main/validation.R")
source("pipeline/modules/hydroclimate_variables.R")
source("pipeline/modules/soil_constants.R")
source("pipeline/modules/terrain_features.R")
source("pipeline/modules/runoff_data.R")
source("pipeline/functions/antecedent_moisture_condition.R")
source("pipeline/functions/cleanup.R")
source("pipeline/functions/clipping.R")
source("pipeline/functions/dimension_reduction.R")
source("pipeline/functions/environment_settings.R")
source("pipeline/functions/evapotranspiration_webscraping.R")
source("pipeline/functions/geostatistical_interpolation.R")
source("pipeline/functions/harmonization.R")
source("pipeline/functions/normalized_roughness.R")
source("pipeline/functions/pipeline_output.R")
source("pipeline/functions/plot_legend.R")
source("pipeline/functions/precipitation_webscraping.R")
source("pipeline/functions/runoff_CNSCS.R")
source("pipeline/functions/runoff_GEE.R")
source("pipeline/functions/topo_wet_index.R")
source("pipeline/functions/validation_runoff.R")
source("pipeline/functions/validation_statistics.R")