#Loading project sources

source("pipeline/modules/antecedent_moisture_data.R")
source("pipeline/modules/dem_data.R")
source("pipeline/modules/evapotranspiration_data.R")
source("pipeline/modules/hydrological_soil_data.R")
source("pipeline/modules/land_cover_data.R")
source("pipeline/modules/precipitation_data.R")
source("pipeline/modules/runoff_data.R")
source("pipeline/modules/topographicWet_index_data.R")
source("pipeline/modules/validation_data.R")
source("pipeline/functions/antecedent_moisture_condition.R")
source("pipeline/functions/cleanup.R")
source("pipeline/functions/clipping.R")
source("pipeline/functions/dimension_reduction.R")
source("pipeline/functions/environment_settings.R")
source("pipeline/functions/evapotranspiration_webscraping.R")
source("pipeline/functions/geostatistical_interpolation.R")
source("pipeline/functions/harmonization.R")
source("pipeline/functions/normalized_roughness.R")
source("pipeline/functions/pipeline_output.R")
source("pipeline/functions/plot_legend.R")
source("pipeline/functions/precipitation_webscraping.R")
source("pipeline/functions/runoff_CNSCS.R")
source("pipeline/functions/runoff_GEE.R")
source("pipeline/functions/topo_wet_index.R")
source("pipeline/functions/validation_runoff.R")
source("pipeline/functions/validation_statistics.R")